remote_theme: pmarsceill/just-the-docs

# Footer content
footer_content: "Copyright &copy;2020 <a href=\"https://twitter.com/Jason_GameDev\">@Jason_GameDev on Twitter</a>"

# Footer edit link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on Prose.io for GitHub"
gh_edit_repository: "https://prose.io/#JasonLu18/UMVC3-ParsecData" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
